apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
  namespace: moderation
  labels:
    app.kubernetes.io/name: moderation
    app.kubernetes.io/component: backend
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: joshuaombasa/issio-moderation:v1.0.0
          ports:
            - containerPort: 4032
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 4032
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 4032
            initialDelaySeconds: 5
            periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
  namespace: moderation
  labels:
    app.kubernetes.io/name: moderation
spec:
  selector:
    app: moderation
  ports:
    - name: http
      protocol: TCP
      port: 4032
      targetPort: 4032
  type: ClusterIP
